apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: py-demo
  name: py-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: py-demo
  type: LoadBalancer
status:
  loadBalancer: {}
